function [out1] = f_UR5_dgrav(q)
%F_UR5_DGRAV
%    [OUT1,Q] = F_UR5_DGRAV(UT1,UT2,UT3,UT4,UT5,UT6)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    20-Dec-2020 14:07:11


Ut1 = q(1);
Ut2 = q(2);
Ut3 = q(3);
Ut4 = q(4);
Ut5 = q(5);
Ut6 = q(6);

out1 = [1.625924115,sin(Ut2).*(-1.7496257625e+1)+7.376422214700001,sin(Ut2).*(-9.714352500000001)-cos(Ut2).*sin(Ut3).*4.4828879625-cos(Ut3).*sin(Ut2).*4.4828879625+2.047785507,sin(Ut2).*(-5.082315750000001)-cos(Ut2).*sin(Ut3).*4.690678477500001-cos(Ut3).*sin(Ut2).*4.690678477500001+1.0713521601,sin(Ut2).*(-5.082315750000001)+cos(Ut4).*(cos(Ut2).*cos(Ut3)-sin(Ut2).*sin(Ut3)).*5.659308067500001e-1+sin(Ut4).*(cos(Ut2).*sin(Ut3)+cos(Ut3).*sin(Ut2)).*5.659308067500001e-1-cos(Ut2).*sin(Ut3).*4.690678477500001-cos(Ut3).*sin(Ut2).*4.690678477500001+1.0713521601,sin(Ut2).*(-7.834020750000001e-1)-sin(Ut5).*(cos(Ut4).*(cos(Ut2).*sin(Ut3)+cos(Ut3).*sin(Ut2))+sin(Ut4).*(cos(Ut2).*cos(Ut3)-sin(Ut2).*sin(Ut3))).*7.585175385000001e-2+cos(Ut4).*(cos(Ut2).*cos(Ut3)-sin(Ut2).*sin(Ut3)).*1.7446825035e-1+sin(Ut4).*(cos(Ut2).*sin(Ut3)+cos(Ut3).*sin(Ut2)).*1.7446825035e-1-cos(Ut2).*sin(Ut3).*7.230340327500001e-1-cos(Ut3).*sin(Ut2).*7.230340327500001e-1+1.6514115741e-1];

end
